---
- name: install the iis web service
  hosts: windows
  tasks:
    - name: "18.1.1 (L1) Ensure 'Prevent enabling lock screen camera' is set to 'Enabled'"
      win_regedit:
              path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization
              name: "NoLockScreenCamera"
              data: "1"
              type: dword
    - name: "17.2.1 (L1) Ensure 'Audit Application Group Management' is set to 'Success and Failure'"
      win_command: Auditpol /set /subcategory:"Application Group Management" /success:enable /failure:enable
    - name: "SCORED | 2.2.10 | PATCH | L1 Ensure Back up files and directories is set to Administrators"
      win_user_right:
              name: SeBackupPrivilege
              users:
                  - Administrators
              action: set
