- name: Installing Apache MSI 

  hosts: windows 

  tasks:
    - name: Install MSI

      win_package: 

        path: C:\httpd-2.2.25-win32-x86-no_ssl.msi

        arguments:
          - /install

          - /passive

          - /norestart
