---
- name: install the iis web service
  hosts: windows
  tasks:
    - name: Ensure new user is present
      win_user:
        name: "{{ user }}"
        password: B0bP4ssw0rd7
        state: present
